### ISSUE TITLE
how to implement (override) anything from `Kameo::Actor` if using the derive macro

### ISSUE THREAD

**Issue by flxo** [tqwewe/kameo#12]
If I declare an actor with the [derive macro](https://docs.rs/kameo/latest/kameo/derive.Actor.html) it's not possible to have an additional impl block that override the default implementations from [here](https://github.com/tqwewe/kameo/blob/a3104deb560e4063d03e48719b4a4f5cbc9f3e2a/crates/kameo/src/actor.rs#L40).

Am I forced to *not* use the derive macro if I need a custom impl for anything in [Actor](https://docs.rs/kameo/latest/kameo/trait.Actor.html)?

**Comment by tqwewe** [comment]
Yep, the derive `Actor` macro doesn't have any customizability, and only implements the Actor trait with the default methods. It's only a convenience macro when you don't need any special functionality.

If you need anything beyond the default behaviour, you'd implement Actor manually yourself, only adding the methods you'd just to modify. None of the methods in the Actor trait are required.

**Comment by flxo** [comment]
Thanks for the clarification!
