### ISSUE TITLE
This method(is_alive() ) always returns false

### ISSUE THREAD

**Issue by xingsongs** [tqwewe/kameo#23]
![image](https://github.com/tqwewe/kameo/assets/6611189/7cb9dacd-f622-47d1-bc34-8cc36332edfa)
log:

![image](https://github.com/tqwewe/kameo/assets/6611189/732afc7c-1db7-4251-88a8-920d89e6c378)

**Comment by tqwewe** [comment]
Thanks, looks like I was missing a `!` in front of the implementation
