### ISSUE TITLE
Sync API

### ISSUE THREAD

**Issue by vadixidav** [tqwewe/kameo#25]
I have a use case where I have an actor managing some GPU state and I want to interact with it from the synchronous context of a winit application. The way I can currently do this is by essentially using a `tokio::sync::oneshot` channel and spawning a task with `tokio` which populates the channel with the result of sending a message to the actor. I suspect that internally `kameo` is probably using a oneshot channel or similar already, and it might be possible to interact with it to receive the response in a sync context.

I would propose a similar API to <https://docs.rs/kameo/latest/kameo/actor/struct.ActorRef.html#method.send>, which could be called `ActorRef::send_sync`. This would return an object that could be polled to see if it is complete. Polling the future directly in a sync context is not possible due to the lack of the async runtime's context that must be passed in.

**Comment by vadixidav** [comment]
This is how I am currently resolving this issue:

```rust
fn actor_sync_request<A, M>(
    actor: ActorRef<A>,
    message: M,
) -> oneshot::Receiver<Result<<A::Reply as Reply>::Ok>>
where
    A: Message<M>,
    M: Send + 'static,
    Result<<A::Reply as Reply>::Ok, SendError<M, <A::Reply as Reply>::Error>>:
        WrapErr<<A::Reply as Reply>::Ok, SendError<M, <A::Reply as Reply>::Error>>,
{
    let (response_tx, response_rx) = oneshot::channel();

    tokio::spawn(async move {
        response_tx.send(actor.send(message).await.wrap_err_with(|| {
            use std::any::type_name;
            format!("{} <-- {}", type_name::<A>(), type_name::<M>())
        }));
    });
    response_rx
}
```

I am using `eyre`, so I also unify the output to `eyre::Result`.

**Comment by tqwewe** [comment]
@vadixidav if you get time, I've made a PR https://github.com/tqwewe/kameo/pull/26. It provides an API for running blocking code within an actors handler.

Does this look like it solves your issue?

**Comment by vadixidav** [comment]
@tqwewe Sadly that solution doesn't necessarily solve my problem. In my case it is the winit application handler that runs on the main thread which is the sync part. Due to that I can't spawn it as an actor. I was hoping I could talk to an actor from outside the actor system in a sync context. I can open another ticket if needed.

**Comment by vadixidav** [comment]
@tqwewe If it helps you, I started splitting out the code that does all of this into its own crate since it is such an investment of time. You can find the current main of the library here: https://github.com/vadixidav/tww/commit/fcaf67bf4d0c7323a5c2b9335872d941bb45a2b3. I am not currently using `kameo`, but you can see how much boilerplate I currently have to support this kind of processing currently. I am using `.await` extensively inside the message handlers as well, which I wasn't sure if that was supported either. If a sync send API is added, I can try `kameo` out again and I will open additional tickets if there are issues I run across.

**Comment by tqwewe** [comment]
Ah okay I understand. The `.send_async()` function in Kameo doesn't need to be awaited, so could be used outside of an asyncronous runtime I believe. However the `.send()` function is async since it awaits a response from the actor. But Tokio's oneshot::Receiver does have a `.blocking_recv()` method to receive the reply in a blocking context without awaiting.

I'll investigate adding a clean API for sending messages and receiving replies in a blocking context.
