### ISSUE TITLE
async handler fn by macro

### ISSUE THREAD

**Issue by flxo** [tqwewe/kameo#4]
The macro **https://github.com/tqwewe/kameo/blob/bb4c8ffdbda8bd4f56cde00ffe8bc38e7d557197/crates/kameo/examples/macro.rs#L19**

example shows how to define a handler `fn` which is *not* async. Is that on purpose and what's the reason for that? I would have expected this to be `async` or return something `impl Future<...>`

**Comment by flxo** [comment]
Ah. nice. Just discovered you support both: `sync` and `async`:
https://github.com/tqwewe/kameo/blob/bb4c8ffdbda8bd4f56cde00ffe8bc38e7d557197/crates/kameo_macros/src/actor.rs#L332

Sorry for the noise.

**Comment by tqwewe** [comment]
No worries! I'll just clarify anyway why it works with/without async:

When using the macro, you can add async or not and it'll work either way.
This code essentially expands to:

```rust
struct Inc { amount: u32 }

impl Message<Counter> for Inc {
    type Reply = Result<i64, Infallible>;
    
    async fn handle(self, state: &mut Counter) -> Self::Reply {
        state.inc(self.amount) // .await is added here if your method is async, otherwise doesn't
    }
}
```
